### ISSUE TITLE
Support for SPI Flash W25N01GV

### ISSUE THREAD

**Issue by ponyatov** [OpenNuvoton/NUC970_NuWriter_CMD#1]
Is it possible to see the source code for nudata/xusb*.bin ?

I need to add support for W25N01GV SLC NAND Flash over SPI, including boot.
Now I cannot even erase SPI Flash without error at the end of a process.

**Comment by ponyatov** [comment]
Maybe NUC976 Internal Boot ROM source code available to check compatibility with W25N01GV command set ?

**Comment by yachen** [comment]
Hi,

The source code is here: https://github.com/OpenNuvoton/NUC970_NuWriter/tree/master/NuWriterFW
Compile using Keil.
NUC970 NuWriter firmware will not support SPI NAND because NUC970 doesn't support boot from SPI NAND.


Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
No. We do not release internal boot ROM source code.
NUC970 does not support boot from SPI NAND.


Sincerely,

Yi-An Chen

**Comment by ponyatov** [comment]
Oops, sorry, our hw engineer made an error.
