### ISSUE TITLE
NuWriter failed randomly

### ISSUE THREAD

**Issue by Tibalt** [OpenNuvoton/NUC970_NuWriter_CMD#10]
After we made our own hardware based on nuc972, the flashing tool failed from time to time. The error message from host linux is as follows:
![企业微信截图_15595489917735](https://user-images.githubusercontent.com/1047435/58786841-0a815d80-861b-11e9-83cf-54b4fad537c8.png)

Now I do not have NHS-972-1-CY-1M55 development board on hand right now but nuwriter worked before for most of the times on the same Linux host.

Could it be a hardware problem?

Regards
Tibalt

**Comment by yachen** [comment]
Hi,

It seems the device is disconnected. Probably some signal issue.
Did you let our H/W FAE review your schematic?


Sincerely,

Yi-An Chen
