### ISSUE TITLE
Random occurrence “ERROR in bulk write: -7 Timeout”

### ISSUE THREAD

**Issue by zhangliang1987** [OpenNuvoton/NUC970_NuWriter_CMD#12]
when i use nuwrier to burn my device,random failed with log "ERROR in bulk write: -7 Timeout"
i need to find the reason ,could you help.

**Comment by yachen** [comment]
Hi,

Are you testing with the pull request you posted?
Which hardware board are you testing with?

Sincerely,

Yi-An Chen

**Comment by zhangliang1987** [comment]
Hi，
I test it on Nuc970 device. it can work.


I can  auto update 4 device or more at once.


But random fail appeared some times. I think it was not related with my change.


Failed reason “ERROR in bulk write: -7 Timeout”


Regards
zhangliang


------------------ 原始邮件 ------------------
发件人: "Yi-An Chen"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 下午4:48
收件人: "OpenNuvoton/NUC970_NuWriter_CMD"<NUC970_NuWriter_CMD@noreply.github.com>;
抄送: "青春的沸腾"<330379704@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [OpenNuvoton/NUC970_NuWriter_CMD] Random occurrence “ERROR in bulk write: -7 Timeout” (#12)




Hi,
 
Are you testing with the pull request you posted?
 Which hardware board are you testing with?
 
Sincerely,
 
Yi-An Chen

**Comment by chenluhong** [comment]
> Hi， I test it on Nuc970 device. it can work. I can auto update 4 device or more at once. But random fail appeared some times. I think it was not related with my change. Failed reason “ERROR in bulk write: -7 Timeout” Regards zhangliang
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Yi-An Chen"<notifications@github.com>; 发送时间: 2019年8月1日(星期四) 下午4:48 收件人: "OpenNuvoton/NUC970_NuWriter_CMD"<NUC970_NuWriter_CMD@noreply.github.com>; 抄送: "青春的沸腾"<330379704@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [OpenNuvoton/NUC970_NuWriter_CMD] Random occurrence “ERROR in bulk write: -7 Timeout” (#12) Hi, Are you testing with the pull request you posted? Which hardware board are you testing with? Sincerely, Yi-An Chen — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Now I meet this problem too, Have you solved this problem?Can you tell me how to solve?thank you very much!

**Comment by zhangliang1987** [comment]
hello，i am sorry i am no longer engaged in embedded softwork,i am not very clear now 。you can see code。我用了一个链表保存usb，然后遍历usb ,再进行烧写。



---Original---

**Comment by chenluhong** [comment]
> hello，i am sorry i am no longer engaged in embedded softwork,i am not very clear now 。you can see code。我用了一个链表保存usb，然后遍历usb ,再进行烧写。
> […](#)
> ---Original--- From: "chenluhong"<notifications@github.com&gt; Date: Tue, Jul 21, 2020 14:28 PM To: "OpenNuvoton/NUC970_NuWriter_CMD"<NUC970_NuWriter_CMD@noreply.github.com&gt;; Cc: "zhangliang1987"<330379704@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [OpenNuvoton/NUC970_NuWriter_CMD] Random occurrence “ERROR in bulk write: -7 Timeout” (#12) Hi， I test it on Nuc970 device. it can work. I can auto update 4 device or more at once. But random fail appeared some times. I think it was not related with my change. Failed reason “ERROR in bulk write: -7 Timeout” Regards zhangliang … ------------------ 原始邮件 ------------------ 发件人: "Yi-An Chen"notifications@github.com; 发送时间: 2019年8月1日(星期四) 下午4:48 收件人: "OpenNuvoton/NUC970_NuWriter_CMD"NUC970_NuWriter_CMD@noreply.github.com; 抄送: "青春的沸腾"330379704@qq.com;"Author"author@noreply.github.com; 主题: Re: [OpenNuvoton/NUC970_NuWriter_CMD] Random occurrence “ERROR in bulk write: -7 Timeout” (#12) Hi, Are you testing with the pull request you posted? Which hardware board are you testing with? Sincerely, Yi-An Chen — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. Now I meet this problem too, Have you solved this problem?Can you tell me how to solve?thank you very much! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢，这个是USB识别的问题吗？昨晚和早上的时候测试的时候发现就有这个问题，然后就在刚刚，我没动什么，然后我再执行擦除emmc的命令，居然能擦除成功了，这个好奇怪，根本不知道问题所在，一下子有问题，一下子问题莫名其妙自动没了

**Comment by zhangliang1987** [comment]
你看源码吧，我想有可能是usb的问题，我们也有出现usb识别的问题后来发现是硬件问题。usb电路没有加保护导致电压不稳定。后来修复了。我这个改动你可以去看源码，源码改动不大，应该不会有问题。



---Original---

**Comment by chenluhong** [comment]
好的，谢谢谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenNuvoton/NUC970_NuWriter_CMD"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 下午3:15
收件人:&nbsp;"OpenNuvoton/NUC970_NuWriter_CMD"<NUC970_NuWriter_CMD@noreply.github.com&gt;;
抄送:&nbsp;"陈禄洪"<190686292@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenNuvoton/NUC970_NuWriter_CMD] Random occurrence “ERROR in bulk write: -7 Timeout” (#12)





 你看源码吧，我想有可能是usb的问题，我们也有出现usb识别的问题后来发现是硬件问题。usb电路没有加保护导致电压不稳定。后来修复了。我这个改动你可以去看源码，源码改动不大，应该不会有问题。 
 
 
 
 ---Original---
