### ISSUE TITLE
ubuntu18.04 install and use nuwriter tool

### ISSUE THREAD

**Issue by njwyj1988** [OpenNuvoton/NUC970_NuWriter_CMD#16]
when I use nuwriter command under ubuntu 18.04, it ocurrs:

root@ubuntu:/home/work# nuwriter -m spi -d NUC977DK62Y.ini -t uboot -a 0xE00000 -w $IMAGE_PATH/uboot.bin -v
cannot open ./../share/nudata/sys_cfg/NUC977DK62Y.ini
initail xusb failed -1
Failed

My steps are:
1) install libusb by:
sudo apt-get install libusb-1.0-0-dev

2) update pkg-config by:
apt-get install pkg-config

3) export IMAGE_PATH
 export IMAGE_PATH=/home/etree/nuc970bsp/image/

4) copy "nuwriter" to system /bin directory

but, I don't know why the command show the error: "cannot open ./../share/nudata/sys_cfg/NUC977DK62Y.ini"

**Comment by yachen** [comment]
That's because NUC977DK62Y.ini doesn't exist in /share/nudata/sys_cfg/NUC977DK62Y.ini.
You must provide a full or relative path that direct to the ini file.

**Comment by njwyj1988** [comment]
> That's because NUC977DK62Y.ini doesn't exist in /share/nudata/sys_cfg/NUC977DK62Y.ini.
> You must provide a full or relative path that direct to the ini file.

thanks! this problem was solved. I execute "nuwriter" command under the "install/bin/" directory, the command run successfully!
`/home/wyj/tool/NUC970_NuWriter_CMD/install/bin# ./nuwriter -m sdram -d NUC977DK62Y.ini -a 0x8000 -w $IMAGE_PATH/970image`

My PC environment and trial steps are:
**`Linux user-OptiPlex-755 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`**
(1) download tools src by:  `git clone https://github.com/OpenNuvoton/NUC970_NuWriter_CMD.git`

(2) install packages: 
apt install automake
apt-get install libusb-1.0-0-dev
apt-get install pkg-config

(3) compile nuwriter source code:
./configure --prefix=$PWD/install
make
meet an error here: 
` cd . && /bin/bash /home/wyj/tool/NUC970_NuWriter_CMD/missing automake-1.15 --foreign
configure.ac:6: error: version mismatch.  This is Automake 1.15.1,
configure.ac:6: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:6: comes from Automake 1.15.  You should recreate
configure.ac:6: aclocal.m4 with aclocal and run automake again.
WARNING: 'automake-1.15' is probably too old.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:355: recipe for target 'Makefile.in' failed
make: *** [Makefile.in] Error 1`

To solve this, according to message: run "aclocal" then "make";

then "make install", the nuwrite tool is ready under the dir: "NUC970_NuWriter_CMD/install/bin"

(4) burn FW to NUC977 by:
`sudo ./nuwriter -m spi -d NUC977DK62Y.ini -a 0x200000 -t data -w /home/work/NUC970_Buildroot-master/output/images/uImage -v`

(5) wait a minute or two, work done!
