### ISSUE TITLE
How to fix Nand erase!

### ISSUE THREAD

**Issue by Layty** [OpenNuvoton/NUC970_NuWriter_CMD#17]
1. I use     nuwriter_cmd erase  , then write kernel and rootfs.ubi ,kernel read error  
![image](https://user-images.githubusercontent.com/14368090/103126356-fdc6cd80-46c8-11eb-8b4b-f30a0f2deb52.png)
2. I use uboot erase chip ,then use nuwriter_cmd  download image, everything is ok.
3. I use nuwriter in win10,  the same error like step 1.
4. I use nuwriter in win10,  select  nand flash , then download image, everything is ok.
![image](https://user-images.githubusercontent.com/14368090/103126421-38c90100-46c9-11eb-8e77-72a2699af7c3.png)
5. I fix common.h to open MSG_DEBUG   ,It info get the correct page size 2048, so how can I use in linux like step 4 in win10
```
#if 1
 #define MSG_DEBUG   printf
 #else
 #define MSG_DEBUG(...)
 #endif
```

**Comment by Layty** [comment]
My nand flash have 2 planes,so how to add this info.
Now I have fix 
```
UXmodem_NAND BlockPerFlash=1,023
```
to
```
UXmodem_NAND BlockPerFlash=2048
```

**Comment by yachen** [comment]
Hi,

So you're having problem to program NAND flash using NuWriter command line tool? Which NAND flash are you using?

Sincerely,

Yi-An Chen
