### ISSUE TITLE
Flashing NuMaker Tomato

### ISSUE THREAD

**Issue by Pfhilip** [OpenNuvoton/NUC970_NuWriter_CMD#18]
Hello,

I have been trying to flash uboot onto the numaker tomato.

I have the tomato connected to my host machine using USB (CN13 on schematic), I have SW2 in the 0 position for USB.

I build uboot using nuc970_tomato_defconfig found here https://github.com/OpenNuvoton/NUC970_U-Boot_v2016.11

then using nuwriter I run

`nuwriter -m spi -d NUC976DK62Y.ini -t uboot -a 0xE00000 -w $UBOOTPATH/u-boot` 

it seems to flash ok but when I change SW2 to the 1 position to boot from SPI flash I don't receive anything on the TX pin of the NU4 header. I'm correct in thinking I should be receiving something on TX?

Thanks

**Comment by yachen** [comment]
You should check console output from CON17.
![tomato](https://user-images.githubusercontent.com/1320946/133011308-18dc71ee-c13b-476c-8b66-345225e68ddb.jpg)

**Comment by Pfhilip** [comment]
I see some output from there, thanks
