### ISSUE TITLE
Bare metal HelloWorld to check "execute from RAM" programming mode

### ISSUE THREAD

**Issue by ponyatov** [OpenNuvoton/NUC970_NuWriter_CMD#2]
Can you provide tiny HelloWorld application source code + compiled binary ?
able to be run w/o any bootloaders by the command like:

```
./nuwriter -m sdram -d NUC972DF62Y.ini -a 0x8000 -w Hello.bin -n
```
and interact via UART0 serial (115200 8n1)

**Comment by ponyatov** [comment]
I tried to run u-boot directly into SDRAM via this like command, but after command successfully executed, nothing is happening on UART console, maybe some other start address should be used.

**Comment by ponyatov** [comment]
PS: I need same bare control consol runs un bare metal mode (w/o any OSes), based on uboot, or written from scratch, to do some experiments with this cool SoC. 

The first one is proving to the boss that NAND chip was selected can't be botted with nuc976 boot rom.

**Comment by ponyatov** [comment]
This HelloWorld will be good as demo bare application able to use nuc as i/o coprocessor for instrumental PC, with start via NuWriter, so source code even can be packed inside this repo

**Comment by yachen** [comment]
U-Boot execution address is 0xe00000.
You can download bare metal hello world sample code/project is at https://github.com/OpenNuvoton/NUC970_NonOS_BSP/tree/master/SampleCode/hello and compile it with Keil.

Sincerely,

Yi-An Chen

**Comment by ponyatov** [comment]
I tried both this commands, have no result console:

```
dpon@dpon:/usr/local/share$ sudo nuwriter -m spi -d NUC976DK62Y.ini -t uboot -a 0xE00000 -w ~/ASDU/doc/test_soft/u-boot.bin -v -n
Write UBOOT ... Passed                                                                                                         
Verify UBOOT... Passed                                                                                                         
dpon@dpon:/usr/local/share$ sudo nuwriter -m spi -d NUC976DK62Y.ini -t data -a 0xE00000 -w ~/ASDU/doc/test_soft/u-boot.bin -v -n
Write DATA ... Passed                                                                                                          
Verify DATA... Passed                                                                                                          
dpon@dpon:/usr/local/share$ 
```

This `u-boot.bin` image is guaranteed works on this board and successfully runs from SPI flash.

I saw this 0xe00000 address both as programming address in SPI mode and in u-boot source code `RAM_TEXT = 0xE00000`, maybe some extra steps must be done to run it.

```
NUC970 IBR 20151008.1735
No Key
Boot from USB
=======================================
Run firmware code
CPU: 300MHz, DDR: 150MHz, SYS: 300MHz, PCLK: 75MHz
Parse NuWriter command line
=======================================
```

**Comment by ponyatov** [comment]
Thanks, it looks like hw problem, firmware boots via sdram on new board just unpacked, and with right load address
