### ISSUE TITLE
Which engineer can tell me how to use it?

### ISSUE THREAD

**Issue by imliubo** [OpenNuvoton/NUC970_NuWriter_CMD#4]
I try use this CMD tool write the image to NUC972,but I do not know how to use it.
I always use PC to write the image before,but I don't want change the operating system when I write the image.So I find this tool.

```bash
NUC970 IBR 20151008.1735

No Key

Boot from USB
```
I set the board boot from USB,but how can I get in the download mode?
I try use the command directly and it log like this:
```bash
$ sudo nuwriter -m nand -d NUC972DF62Y.ini -t uboot -a 0x200 -w ./nand_uboot_spl.bin -v
device not found: Resource temporarily unavailable
initail xusb failed -1
Failed
```
It means I need install driver or somethings?
Which engineer can tell me how to use it step by step,I just want I can always use the ubuntu to develop it,not when I write the image I need change the OS to do it.
thanks~

**Comment by yachen** [comment]
Hi,

Do you see a new “Winbond Electronics Corp.” entry  of lsusb output after plug in the board?


Sincerely,

Yi-An Chen




===========================================================================================
The privileged confidential information contained in this email is intended for use only by the addressees as indicated by the original sender of this email. If you are not the addressee indicated in this email or are not responsible for delivery of the email to such a person, please kindly reply to the sender indicating this fact and delete all copies of it from your computer and network server immediately. Your cooperation is highly appreciated. It is advised that any unauthorized use of confidential information of Nuvoton is strictly prohibited; and any information in this email irrelevant to the official business of Nuvoton shall be deemed as neither given nor endorsed by Nuvoton.

**Comment by yachen** [comment]
Hi,

Are you using virtual machine or native Linux?

Sincerely,

Yi-An Chen

**Comment by imliubo** [comment]
Hi,
I use native Linux not virtual machine.
And I use [coidea's](https://item.taobao.com/item.htm?spm=a1z10.1-c-s.w4004-18262286049.8.4d044bd1htmmsa&id=567511201497) NUC972 core board.
It can use NuWriter write images on windows PC.

Thank you for your quick reply.

**Comment by imliubo** [comment]
Hi,
I solved this problem.It was hardware error has occurred.
Finally,it's fixed!I can develop and write it on the same OS.
Thanks for helping me,I will closed this issue.  
Have a nice day!

**Comment by imliubo** [comment]
Hi,
I think I meet some new question,so I reopen this issue.
The problem is this:
![default](https://user-images.githubusercontent.com/26544331/51436344-30d6da00-1cc6-11e9-8e4b-40803af84d8f.png)
I solved the hardware cann't detect problem,but I don't this problem means.
What‘s going on with this?

**Comment by schung1218** [comment]
Hi,
you can try, file name use absolute path

**Comment by imliubo** [comment]
Hi,
It doesn't work too.
Have you used this CMD tool?I almost give up to use it...Too difficult to me.

**Comment by schung1218** [comment]
Hi,
help me to dump output message from coidea's NUC972 core board.
Firstly, you should see as below

NUC970 IBR 20151008.1735
Boot from USB
=======================================
Run firmware code
CPU: 300MHz, DDR: 150MHz, SYS: 300MHz, PCLK: 75MHz
Parse NuWriter command line
=======================================

**Comment by imliubo** [comment]
Hi,
When I run command no messages be print.
But I use the NuWriter(GUI) on PC,it can print some message.
This is use the command line on Ubuntu.
![default](https://user-images.githubusercontent.com/26544331/51537088-80fd9a00-1e88-11e9-809a-f8605f71faca.png)
This is use the NuWriter(GUI) on Windows 10.
![default](https://user-images.githubusercontent.com/26544331/51537154-c0c48180-1e88-11e9-9106-4f995bd05100.png)
The hardware setting was same,and the board can be detected.
![default](https://user-images.githubusercontent.com/26544331/51537427-7bed1a80-1e89-11e9-8220-76ee11978597.png)
Did this command line tool had some connecting hardware command like the NuWriter(GUI)?

**Comment by schung1218** [comment]
Hi,
Yes, commnad line tool like nuwriter gui.
Your procedure look fine. But nuc972 board receive firmware code failed from PC. So I will be to duplicate it. what ubuntu version?

**Comment by imliubo** [comment]
Hi,
It's ubuntu16.04.
Thanks for do it.

**Comment by schung1218** [comment]
I have been tested nuwriter command line tools, it is fine on my PC with ubuntu-16.04.5-desktop-i386.iso and ubuntu-16.04.5-desktop-i386.iso. 
Maybe it is some error occurs on USB bus. you can try to re-install libusb from https://github.com/libusb/libusb/releases to download lastest version.

**Comment by imliubo** [comment]
Hi,
I try it,but it still not work.And I use another computer to do this,the result was same.I suspect that there is something wrong with my hardware, but use the NuWriter(GUI) on Windows can be work.The image is I use another computer,the error was same after I install the libusb of latest release version.
![default](https://user-images.githubusercontent.com/26544331/51611887-43b60c80-1f5b-11e9-9556-ce074edd660d.png)
Maybe I should give up it.Thanks for helping me.
Thank you @schung1218 and you @yachen .

**Comment by yachen** [comment]
Close since there's no further discussion for a while. Reopen if necessary.

**Comment by Tibalt** [comment]
now i am using nuwriter on Linux on nhs-972-1-cy-1M55.

I have seen your problem too and i solved by put cfg2 in correct position. Do not why but solved it.

Regards
tibalt

**Comment by yachen** [comment]
Cfg2 on dev board controls the system clock, Please set it to OFF so UPLL is used as system clock.
