### ISSUE TITLE
cannot write nand flash

### ISSUE THREAD

**Issue by houxd** [OpenNuvoton/NUC970_NuWriter_CMD#5]
when i compile it accord readme.md
i get this error:
./nuwriter  -m nand -d NUC972DF62Y.ini -t uboot -a 0x200 -w ../../../../wt/uboot/u-boot.bin -v   
Cannot find NAND(2048,0)
Failed

**Comment by schung1218** [comment]
Hi,
you need to change power-on setting for NAND Flash Page Size selection(cfg6=1,cfg7=1) and NAND Flash ECC Type Selection( cfg8=1,cfg9=1).

**Comment by houxd** [comment]
thanks, it can work.
