### ISSUE TITLE
strange env in uboot after flash env.txt by nuwriter cmd

### ISSUE THREAD

**Issue by Tibalt** [OpenNuvoton/NUC970_NuWriter_CMD#6]
Hi, guys
The problem is strange. I flashed [envforubifs.txt](https://github.com/OpenNuvoton/NUC970_NuWriter_CMD/files/3193532/envforubifs.txt) by cmd `/nuwriter -m nand -d NUC972DF61Y.ini -t env -a 0x80000 -w $IMAGE_PATH/envforubifs.txt -v`   into nand and after I boot the system from nand. 
Boot failed because the last 0 is missing in bootcmd="nboot 0x7fc0 0 0x200000;bootm 0x7fc".

Then I checked all the envs and found that the last character of all envs are missing. 

can anybody give me a clue?

Regards
Tibalt

**Comment by houxd** [comment]
every line of envforubifs.txt must append a space at end, it will worked.  i think this is a bug.

**Comment by Tibalt** [comment]
"space" before or after CRLF(LF)?

**Comment by yachen** [comment]
Hi @Tibalt , we're fixing this issue and will release today.

**Comment by Tibalt** [comment]
> Hi @Tibalt , we're fixing this issue and will release today.

Thanks!

**Comment by yachen** [comment]
Hi @Tibalt, please let me know if yesterday's patch fix this issue in your environment. Thanks.

**Comment by Tibalt** [comment]
> Hi @Tibalt, please let me know if yesterday's patch fix this issue in your environment. Thanks.

Thanks, now it works for me!
