### ISSUE TITLE
INFO_T doesn't match between nuwriter and nuwriter_fw

### ISSUE THREAD

**Issue by qianfan-Zhao** [OpenNuvoton/NUC970_NuWriter_CMD#8]
Patch:
diff --git a/Serial.h b/Serial.h
index 9e8a93a..7be1ea1 100644
--- a/Serial.h
+++ b/Serial.h
@@ -72,6 +72,7 @@ typedef struct _INFO_T {
        DWORD   Nand_uBlockPerFlash;
        DWORD   Nand_uBadBlockCount;
        DWORD   Nand_uSpareSize;
+       DWORD   Nand_uIsUserConfig;
        DWORD   SPI_ID;
        DWORD   EMMC_uBlock;
        DWORD   EMMC_uReserved;

**Comment by schung1218** [comment]
Hi,
Nand_uIsUserConfig is used for Mass production mode, NUC970_NuWriter_CMD does not support Mass production mode.

**Comment by qianfan-Zhao** [comment]
@schung1218 

Had you tried run the laster Nuwriter-FW firmware on linux platform by using Nuwriter_CMD?

The INFO_T has different defines between FW and CMD, so the length of INFO_T  is doesn't match, the value of sizeof(INFO_T) is 44 in FW, but CMD is 40.

The FW try get the full INFO_T once, and the host only send 40 bytes. That's will make the FW dead in while loop.

```
void UXmodem_INFO()
{
    //int i;
    INFO_T info;
    UINT8 *ptr=(UINT8 *)&info;
    memset((char *)&info,0x0,sizeof(INFO_T));

    MSG_DEBUG("Receive INFO flash Image ...\n");
    while(1) {
        if(Bulk_Out_Transfer_Size>=sizeof(INFO_T)) {
            usb_recv(ptr,sizeof(INFO_T));
            break;
        }
    }
```

**Comment by schung1218** [comment]
Hi @qianfan-Zhao 
NUC970_NuWriter_CMD cannot run laster Nuwriter-FW firmware.

**Comment by qianfan-Zhao** [comment]
@schung1218 I had fixed somethings and now it can run laster Nuwriter-FW, at least download to DRAM is worked.
